name: Deploy Staging React App to Ubuntu Server

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Ubuntu server
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key

          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "
          cd /var/www/staging &&
          sudo git pull origin staging &&
          sudo npm i &&
          sudo npm run build &&	
          sudo systemctl reload apache2"
